language: php
php: 7.0
before-install:
    - sudo apt-get install mariadb-server mariadb-client
script:
    - which mysqld
    - which mysql
    - mysql -V
    - export XATAFACE=`pwd`
    - cd ..
    - mkdir tests
    - cd tests
    - bash $XATAFACE/.travis/test_create.sh
    - rm -rf testapp
    - bash $XATAFACE/tests/runtests.sh