name: Run Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: shogo82148/actions-setup-mysql@v1
      with:
        mysql-version: '8.0'
        auto-start: false
    - name: "Print MYSQL Info"
      run: mysql --version
    - name: Run Tests
      run: composer test
